[package]
name = "testdriver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "1.3.0"
async-trait = "0.1.51"
futures = "0.3.18"
tokio = { version = "1.14.0", features = ["test-util", "full"] }
tracing = { git = "https://github.com/tokio-rs/tracing.git", branch = "master" }
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing.git", branch = "master", features=["env-filter"] }
